# Generated by Django 5.0.1 on 2024-01-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="faq",
            name="description",
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
