# Generated by Django 5.0.1 on 2024-01-19 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_remove_faq_description_alter_service_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquiryform",
            old_name="services",
            new_name="service",
        ),
    ]
