# Generated by Django 5.0.1 on 2024-01-19 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_rename_services_enquiryform_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="description",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
