# Generated by Django 5.0.1 on 2024-01-19 19:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_faq_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="updates",
            name="content",
        ),
        migrations.AddField(
            model_name="updates",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
